theme: minima
title: SteelMango
description: Blog of Computer Science/Cyber Security Explained Simply with Computational Thinking!
header_pages:
  - projects.md
  - writeups.md
  - notes.md
  - readings.md
  - about.md