theme: minima
title: SteelMango
description: Penelope Farquharson | Blog of Computer Science/Cyber Security Explained simply with Computational Thinking!
header_pages:
  - projects.md
  - writeups.md
  - readings.md
  - about.md